version: "3.8"
services:
  frontend:
    image: hubnexusai/gpfx-frontend:latest
    networks:
      - digital_network
      - traefik_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.gpfx.rule=Host(`fx.painelzap.com`)
        - traefik.http.routers.gpfx.entrypoints=websecure
        - traefik.http.services.gpfx.loadbalancer.server.port=80
        - traefik.http.routers.gpfx.service=gpfx
        - traefik.http.routers.gpfx.tls.certresolver=le
        - com.centurylinklabs.watchtower.enable=true
  backend:
    image: hubnexusai/gpfx-backend:latest
    networks:
      - digital_network
      - traefik_public
    environment:
      - DATABASE_URL=postgresql://postgres:hub123nexusai@postgres:5432/saas_gerenciamento_fx
      - SECRET_KEY=gpfx-secret-key-2026-production
      - INTERNAL_API_KEY=gpfx-internal-key-2026
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MINIO_ENDPOINT=s3.hubnexusai.com
      - MINIO_ACCESS_KEY=574184765162
      - MINIO_SECRET_KEY=8332bdeca11c80fe91685492
      - MINIO_BUCKET=appgerenciamentofx
      - MINIO_USE_SSL=true
      - REDIS_URL=redis://redis:6379/5
      - N8N_WEBHOOK_URL=https://n8n.painelzap.com/webhook
      - ACCESS_TOKEN_EXPIRE_MINUTES=480
      - REFRESH_TOKEN_EXPIRE_DAYS=30
      - MTCONNECT_API_KEY=FfDghn2d9it8Mesmo2uVYh2YXdYgDAAm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.gpfx-api.rule=Host(`api.painelzap.com`)
        - traefik.http.routers.gpfx-api.entrypoints=websecure
        - traefik.http.services.gpfx-api.loadbalancer.server.port=8000
        - traefik.http.routers.gpfx-api.service=gpfx-api
        - traefik.http.routers.gpfx-api.tls.certresolver=le
        - com.centurylinklabs.watchtower.enable=true
networks:
  digital_network:
    external: true
    name: digital_network
  traefik_public:
    external: true
    name: traefik_public